User-agent: *
Disallow: {PATH}*page=SN_*
Disallow: {PATH}*tpl=*
Disallow: {PATH}*XTCsid*
Disallow: {PATH}*currency=*
Disallow: {PATH}*do=CreateGuest*
Disallow: {PATH}*do=CreateRegistree*
Disallow: {PATH}*switch_country=*
Disallow: {PATH}*filter_fv_id*
Disallow: {PATH}*filter_id*
Disallow: {PATH}*filter_price_max*
Disallow: {PATH}*filter_price_min*
Disallow: {PATH}*listing_count*
Disallow: {PATH}*listing_sort*
Disallow: {PATH}*gm_boosted_category*
Disallow: {PATH}*gm_boosted_product*
Disallow: {PATH}*sort=*
Disallow: {PATH}*view_mode*
Disallow: {PATH}actindo/
Disallow: {PATH}admin/
Disallow: {PATH}cache/
Disallow: {PATH}currency/
Disallow: {PATH}download/
Disallow: {PATH}export/
Disallow: {PATH}logfiles/
Disallow: {PATH}includes/
Disallow: {PATH}media/content/
Disallow: {PATH}pub/
Disallow: {PATH}sort/
Disallow: {PATH}templates_c/
Disallow: {PATH}address_book_process.php
Disallow: {PATH}account.php
Disallow: {PATH}address_book.php
Disallow: {PATH}account_edit.php
Disallow: {PATH}account_edit_process.php
Disallow: {PATH}account_history.php
Disallow: {PATH}account_history_info.php
Disallow: {PATH}advanced_search.php
Disallow: {PATH}advanced_search_result.php
Disallow: {PATH}callback/
Disallow: {PATH}checkout_address.php
Disallow: {PATH}checkout_confirmation.php
Disallow: {PATH}checkout_payment.php
Disallow: {PATH}checkout_payment_address.php
Disallow: {PATH}checkout_process.php
Disallow: {PATH}checkout_shipping.php
Disallow: {PATH}checkout_shipping_address.php
Disallow: {PATH}checkout_success.php
Disallow: {PATH}checkout_vrepay_elv.php
Disallow: {PATH}checkout_vrepay_giropay.php
Disallow: {PATH}checkout_vrepay_kreditkarte.php
Disallow: {PATH}create_account.php
Disallow: {PATH}create_account_process.php
Disallow: {PATH}create_account_success.php
Disallow: {PATH}create_guest_account.php
Disallow: {PATH}display_vvcodes.php
Disallow: {PATH}download.php
Disallow: {PATH}ext/
Disallow: {PATH}fax.html
Disallow: {PATH}*gambio_installer*/
Disallow: {PATH}gambio_updater/
Disallow: {PATH}gm/
Disallow: {PATH}gm_account_delete.php
Disallow: {PATH}gm_css_monitor.php
Disallow: {PATH}gm_opensearch.php
Disallow: {PATH}gm_price_offer.php
Disallow: {PATH}gm_privacy.php
Disallow: {PATH}GProtector/
Disallow: {PATH}gv_redeem.php
Disallow: {PATH}gv_send.php
Disallow: {PATH}heidelpay-curl.class.php
Disallow: {PATH}heidelpay-frontend.css.php
Disallow: {PATH}heidelpay-frontend.js.php
Disallow: {PATH}heidelpay-listener.php
Disallow: {PATH}heidelpay-sender.php
Disallow: {PATH}hp_example_banner.html
Disallow: {PATH}import/
Disallow: {PATH}inc/
Disallow: {PATH}lang/
Disallow: {PATH}lettr/
Disallow: {PATH}login.php
Disallow: {PATH}login_admin.php
Disallow: {PATH}logoff.php
Disallow: {PATH}newsletter.php
Disallow: {PATH}notify_vrepay_elv.php
Disallow: {PATH}notify_vrepay_giropay.php
Disallow: {PATH}notify_vrepay_kreditkarte.php
Disallow: {PATH}password_double_opt.php
Disallow: {PATH}PdfCreator/
Disallow: {PATH}popup_coupon_help.php
Disallow: {PATH}popup_image.php
Disallow: {PATH}popup_search_help.php
Disallow: {PATH}print_order.php
Disallow: {PATH}print_product_info.php
Disallow: {PATH}product_reviews.php
Disallow: {PATH}product_reviews_info.php
Disallow: {PATH}product_reviews_write.php
Disallow: {PATH}redirect.php
Disallow: {PATH}release_info.php
Disallow: {PATH}request_port.php
Disallow: {PATH}reviews.php
Disallow: {PATH}send_order.php
Disallow: {PATH}shop.php
Disallow: {PATH}shopgate/
Disallow: {PATH}shopping_cart.php
Disallow: {PATH}show_product_thumbs.php
Disallow: {PATH}ssl_check.php
Disallow: {PATH}StyleEdit/
Disallow: {PATH}system/
Disallow: {PATH}GXEngine/
Disallow: {PATH}GXMainComponents/
Disallow: {PATH}GXUserComponents/
Disallow: {PATH}version_info/
Disallow: {PATH}vrepay_kreditkarte.php
Disallow: {PATH}wish_list.php
Disallow: {PATH}withdrawal.php
Disallow: {PATH}wpcallback.php
Disallow: {PATH}xtbcallback.php