<?php
/* --------------------------------------------------------------
	ssl_check.lang.inc.php 2015-01-05 gm
	Gambio GmbH
	http://www.gambio.de
	Copyright (c) 2015 Gambio GmbH
	Released under the GNU General Public License (Version 2)
	[http://www.gnu.org/licenses/gpl-2.0.html]
   --------------------------------------------------------------
*/

$t_language_text_section_content_array = array
(
	'heading_ssl_check' => 'Note on security',
	'text_infobox' => 'The simulator scenario language session ID generated by your browser is checked for a secure page each time you access the Internet.<br /><br />This check guarantees that access is made by your browser and not from another browser.',
	'text_information' => 'Our security check has indicated that your browser has changed the SSL session ID during your visit to the site.<br /><br />For security reasons we must ask you to register again.<br /><br />Some browsers, e.g. Konqueror 3.1, cannot generate the Secure SSL session ID automatically and this is a requirement. If you use one of these browsers, please update it to the latest version or install another browser, e.g. <a href="http://www.microsoft.com/ie/" target="_blank">Microsoft Internet Explorer</a>, <a href="http://channels.netscape.com/ns/browsers/download_other.jsp" target="_blank">Netscape</a> or <a href="http://www.mozilla.org/releases/" target="_blank">Mozilla</a>. Once you have updated to one of these browsers, you should be able to use our store in the knowledge that you are doing so securely.br><br />This security measure is used to protect you. Please accept our apologies for any inconvenience if you experience further problems.',
	'title_infobox' => 'Privacy and security'
);