DROP TABLE IF EXISTS `admin_access`;
CREATE TABLE `admin_access` (
  `customers_id` varchar(32) NOT NULL DEFAULT '0',
  `configuration` int(1) NOT NULL DEFAULT '0',
  `modules` int(1) NOT NULL DEFAULT '0',
  `countries` int(1) NOT NULL DEFAULT '0',
  `currencies` int(1) NOT NULL DEFAULT '0',
  `zones` int(1) NOT NULL DEFAULT '0',
  `geo_zones` int(1) NOT NULL DEFAULT '0',
  `tax_classes` int(1) NOT NULL DEFAULT '0',
  `tax_rates` int(1) NOT NULL DEFAULT '0',
  `accounting` int(1) NOT NULL DEFAULT '0',
  `backup` int(1) NOT NULL DEFAULT '0',
  `cache` int(1) NOT NULL DEFAULT '0',
  `server_info` int(1) NOT NULL DEFAULT '0',
  `whos_online` int(1) NOT NULL DEFAULT '0',
  `languages` int(1) NOT NULL DEFAULT '0',
  `define_language` int(1) NOT NULL DEFAULT '0',
  `orders_status` int(1) NOT NULL DEFAULT '0',
  `shipping_status` int(1) NOT NULL DEFAULT '0',
  `module_export` int(1) NOT NULL DEFAULT '0',
  `customers` int(1) NOT NULL DEFAULT '0',
  `create_account` int(1) NOT NULL DEFAULT '0',
  `customers_status` int(1) NOT NULL DEFAULT '0',
  `orders` int(1) NOT NULL DEFAULT '0',
  `campaigns` int(1) NOT NULL DEFAULT '0',
  `print_packingslip` int(1) NOT NULL DEFAULT '0',
  `print_order` int(1) NOT NULL DEFAULT '0',
  `popup_memo` int(1) NOT NULL DEFAULT '0',
  `coupon_admin` int(1) NOT NULL DEFAULT '0',
  `listcategories` int(1) NOT NULL DEFAULT '0',
  `gv_queue` int(1) NOT NULL DEFAULT '0',
  `gv_mail` int(1) NOT NULL DEFAULT '0',
  `gv_sent` int(1) NOT NULL DEFAULT '0',
  `validproducts` int(1) NOT NULL DEFAULT '0',
  `validcategories` int(1) NOT NULL DEFAULT '0',
  `mail` int(1) NOT NULL DEFAULT '0',
  `categories` int(1) NOT NULL DEFAULT '0',
  `new_attributes` int(1) NOT NULL DEFAULT '0',
  `products_attributes` int(1) NOT NULL DEFAULT '0',
  `manufacturers` int(1) NOT NULL DEFAULT '0',
  `reviews` int(1) NOT NULL DEFAULT '0',
  `specials` int(1) NOT NULL DEFAULT '0',
  `stats_products_expected` int(1) NOT NULL DEFAULT '0',
  `stats_products_viewed` int(1) NOT NULL DEFAULT '0',
  `stats_products_purchased` int(1) NOT NULL DEFAULT '0',
  `stats_customers` int(1) NOT NULL DEFAULT '0',
  `stats_sales_report` int(1) NOT NULL DEFAULT '0',
  `stats_campaigns` int(1) NOT NULL DEFAULT '0',
  `banner_manager` int(1) NOT NULL DEFAULT '0',
  `banner_statistics` int(1) NOT NULL DEFAULT '0',
  `module_newsletter` int(1) NOT NULL DEFAULT '0',
  `start` int(1) NOT NULL DEFAULT '0',
  `content_manager` int(1) NOT NULL DEFAULT '0',
  `content_preview` int(1) NOT NULL DEFAULT '0',
  `credits` int(1) NOT NULL DEFAULT '0',
  `blacklist` int(1) NOT NULL DEFAULT '0',
  `orders_edit` int(1) NOT NULL DEFAULT '0',
  `popup_image` int(1) NOT NULL DEFAULT '0',
  `csv_backend` int(1) NOT NULL DEFAULT '0',
  `products_vpe` int(1) NOT NULL DEFAULT '0',
  `cross_sell_groups` int(1) NOT NULL DEFAULT '0',
  `listproducts` int(1) NOT NULL DEFAULT '0',
  `gm_scroller` int(1) NOT NULL DEFAULT '0',
  `gm_pdf` int(1) NOT NULL DEFAULT '0',
  `gm_id_starts` int(1) NOT NULL DEFAULT '0',
  `gm_pdf_order` int(1) NOT NULL DEFAULT '0',
  `gm_pdf_action` int(1) NOT NULL DEFAULT '0',
  `gm_emails` int(1) NOT NULL DEFAULT '0',
  `gm_emails_preview` int(1) NOT NULL DEFAULT '0',
  `gm_counter` int(1) NOT NULL DEFAULT '0',
  `gm_counter_action` int(1) NOT NULL DEFAULT '0',
  `gm_meta` int(1) NOT NULL DEFAULT '0',
  `gm_meta_action` int(1) NOT NULL DEFAULT '0',
  `gm_analytics` int(1) NOT NULL DEFAULT '0',
  `gm_bookmarks` int(1) NOT NULL DEFAULT '0',
  `gm_bookmarks_action` int(1) NOT NULL DEFAULT '0',
  `gm_laws` int(1) NOT NULL DEFAULT '0',
  `gm_logo` int(1) NOT NULL DEFAULT '0',
  `gm_security` int(1) NOT NULL DEFAULT '0',
  `gm_style_edit` int(1) NOT NULL DEFAULT '0',
  `gm_send_order` int(1) NOT NULL DEFAULT '0',
  `gm_order_menu` int(1) NOT NULL DEFAULT '0',
  `gm_miscellaneous` int(1) NOT NULL DEFAULT '0',
  `gm_lang_edit` int(1) NOT NULL DEFAULT '0',
  `gm_sitemap` int(1) NOT NULL DEFAULT '0',
  `gm_sitemap_creator` int(1) NOT NULL DEFAULT '0',
  `gm_sql` int(1) NOT NULL DEFAULT '0',
  `gm_offline` int(1) NOT NULL DEFAULT '0',
  `gm_lightbox` int(1) NOT NULL DEFAULT '0',
  `gm_seo_boost` int(1) NOT NULL DEFAULT '0',
  `gm_trusted_shop_id` int(1) NOT NULL DEFAULT '0',
  `gm_opensearch` int(1) NOT NULL DEFAULT '0',
  `gm_opensearch_action` int(1) NOT NULL DEFAULT '0',
  `gm_module_export` int(1) NOT NULL DEFAULT '0',
  `gm_backup_files_zip` int(1) NOT NULL DEFAULT '0',
  `gm_janolaw` int(1) NOT NULL DEFAULT '0',
  `gm_module_part_export` int(1) NOT NULL DEFAULT '0',
  `gm_product_export` int(1) NOT NULL DEFAULT '0',
  `gm_gprint` int(1) NOT NULL DEFAULT '0',
  `gm_gprint_download` int(1) NOT NULL DEFAULT '0',
  `gm_gmotion` int(1) NOT NULL DEFAULT '0',
  `xml_export` int(1) NOT NULL DEFAULT '0',
  `gm_feature_control` int(1) NOT NULL DEFAULT '0',
  `properties` int(1) NOT NULL DEFAULT '0',
  `properties_combis` int(1) NOT NULL DEFAULT '0',
  `request_port` int(1) NOT NULL DEFAULT '0',
  `gm_slider` int(1) NOT NULL DEFAULT '0',
  `template_configuration` int(1) NOT NULL DEFAULT '0',
  `quantity_units` int(1) NOT NULL DEFAULT '0',
  `show_logs` int(1) NOT NULL DEFAULT '0',
  `robots_download` int(1) NOT NULL DEFAULT '0',
  `clear_cache` int(1) NOT NULL DEFAULT '0',
  `directory_scan` int(1) NOT NULL DEFAULT '0',
  `yoochoose` int(1) NOT NULL DEFAULT '0',
  `yatego` int(1) NOT NULL DEFAULT '0',
  `gm_invoicing` int(1) NOT NULL DEFAULT '0',
  `brickfox` int(1) NOT NULL DEFAULT '0',
  `phpminiadmin` int(1) NOT NULL DEFAULT '0',
  `minisql` int(1) NOT NULL DEFAULT '0',
  `ekomi` int(1) NOT NULL DEFAULT '0',
  `magnalister` int(1) NOT NULL DEFAULT '0',
  `mobile` int(1) NOT NULL DEFAULT '0',
  `shopgate` int(1) NOT NULL DEFAULT '0',
  `mediafinanz` int(1) NOT NULL DEFAULT '0',
  `lettr_de` int(1) NOT NULL DEFAULT '0',
  `admin_javascript` int(1) NOT NULL DEFAULT '0',
  `hermes_collection` int(1) NOT NULL DEFAULT '0',
  `hermes_list` int(1) NOT NULL DEFAULT '0',
  `hermes_info` int(1) NOT NULL DEFAULT '0',
  `hermes_order` int(1) NOT NULL DEFAULT '0',
  `hermes_config` int(1) NOT NULL DEFAULT '0',
  `iloxx` int(1) NOT NULL DEFAULT '0',
  `orders_iloxx` int(1) NOT NULL DEFAULT '0',
  `csv` int(1) NOT NULL DEFAULT '0',
  `paypal_config` int(1) NOT NULL DEFAULT '0',
  `paypal_logs` int(1) NOT NULL DEFAULT '0',
  `print_intraship_label` int(1) NOT NULL DEFAULT '0',
  `intraship` int(1) NOT NULL DEFAULT '0',
  `klarna_config` int(1) NOT NULL DEFAULT '0',
  `protectedshops` int(1) NOT NULL DEFAULT '0',
  `itrecht_config` int(1) NOT NULL DEFAULT '0',
  `withdrawals` int(1) NOT NULL DEFAULT '0',
  `findologic_config` int(1) NOT NULL DEFAULT '0',
  `amazonadvpay` int(1) NOT NULL DEFAULT '0',
  `payone_config` int(1) NOT NULL DEFAULT '0',
  `payone_logs` int(1) NOT NULL DEFAULT '0',
  `parcel_services` int(1) NOT NULL DEFAULT '0',
  `timer` int(1) NOT NULL DEFAULT '0',
  `admin` int(1) NOT NULL DEFAULT '0',
  `emails` int(1) NOT NULL DEFAULT '0',
  `heidelpaygw` int(1) NOT NULL DEFAULT '0',
  `mailbeez` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`customers_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `admin_access` SET
	`customers_id` = 'groups',
	`configuration` = 1,
	`modules` = 1,
	`countries` = 1,
	`currencies` = 1,
	`zones` = 1,
	`geo_zones` = 1,
	`tax_classes` = 1,
	`tax_rates` = 1,
	`accounting` = 1,
	`backup` = 1,
	`cache` = 1,
	`server_info` = 1,
	`whos_online` = 1,
	`languages` = 1,
	`define_language` = 1,
	`orders_status` = 1,
	`shipping_status` = 1,
	`module_export` = 1,
	`customers` = 1,
	`create_account` = 1,
	`customers_status` = 1,
	`orders` = 1,
	`campaigns` = 2,
	`print_packingslip` = 2,
	`print_order` = 2,
	`popup_memo` = 3,
	`coupon_admin` = 3,
	`listcategories` = 3,
	`gv_queue` = 3,
	`gv_mail` = 3,
	`gv_sent` = 3,
	`validproducts` = 3,
	`validcategories` = 4,
	`mail` = 4,
	`categories` = 4,
	`new_attributes` = 4,
	`products_attributes` = 2,
	`manufacturers` = 4,
	`reviews` = 2,
	`specials` = 2,
	`stats_products_expected` = 2,
	`stats_products_viewed` = 2,
	`stats_products_purchased` = 5,
	`stats_customers` = 5,
	`stats_sales_report` = 5,
	`stats_campaigns` = 5,
	`banner_manager` = 5,
	`banner_statistics` = 5,
	`module_newsletter` = 5,
	`start` = 5,
	`content_manager` = 2,
	`content_preview` = 2,
	`credits` = 2,
	`blacklist` = 2,
	`orders_edit` = 2,
	`popup_image` = 2,
	`csv_backend` = 2,
	`products_vpe` = 2,
	`cross_sell_groups` = 2,
	`listproducts` = 1,
	`gm_scroller` = 1,
	`gm_pdf` = 1,
	`gm_id_starts` = 1,
	`gm_pdf_order` = 1,
	`gm_pdf_action` = 1,
	`gm_emails` = 1,
	`gm_emails_preview` = 1,
	`gm_counter` = 1,
	`gm_counter_action` = 1,
	`gm_meta` = 1,
	`gm_meta_action` = 1,
	`gm_analytics` = 1,
	`gm_bookmarks` = 1,
	`gm_bookmarks_action` = 1,
	`gm_laws` = 1,
	`gm_logo` = 1,
	`gm_security` = 1,
	`gm_style_edit` = 1,
	`gm_send_order` = 1,
	`gm_order_menu` = 1,
	`gm_miscellaneous` = 1,
	`gm_lang_edit` = 1,
	`gm_sitemap` = 1,
	`gm_sitemap_creator` = 1,
	`gm_sql` = 1,
	`gm_offline` = 1,
	`gm_lightbox` = 1,
	`gm_seo_boost` = 1,
	`gm_trusted_shop_id` = 1,
	`gm_opensearch` = 1,
	`gm_opensearch_action` = 1,
	`gm_module_export` = 1,
	`gm_backup_files_zip` = 1,
	`gm_janolaw` = 1,
	`gm_module_part_export` = 1,
	`gm_product_export` = 1,
	`gm_gprint` = 1,
	`gm_gprint_download` = 1,
	`gm_gmotion` = 1,
	`xml_export` = 1,
	`gm_feature_control` = 1,
	`properties` = 1,
	`properties_combis` = 1,
	`request_port` = 1,
	`gm_slider` = 1,
	`template_configuration` = 1,
	`quantity_units` = 1,
	`show_logs` = 1,
	`robots_download` = 1,
	`clear_cache` = 1,
	`directory_scan` = 1,
	`yoochoose` = 1,
	`yatego` = 1,
	`gm_invoicing` = 1,
	`brickfox` = 1,
	`phpminiadmin` = 1,
	`minisql` = 1,
	`ekomi` = 1,
	`magnalister` = 1,
	`mobile` = 1,
	`shopgate` = 1,
	`mediafinanz` = 1,
	`lettr_de` = 1,
	`admin_javascript` = 1,
	`hermes_collection` = 1,
	`hermes_list` = 1,
	`hermes_info` = 1,
	`hermes_order` = 1,
	`hermes_config` = 1,
	`iloxx` = 1,
	`orders_iloxx` = 1,
	`csv` = 1,
	`paypal_config` = 1,
	`paypal_logs` = 1,
	`print_intraship_label` = 1,
	`intraship` = 1,
	`klarna_config` = 1,
	`protectedshops` = 1,
	`itrecht_config` = 1,
	`withdrawals` = 1,
	`findologic_config` = 1,
	`amazonadvpay` = 1,
	`payone_config` = 1,
	`payone_logs` = 1,
	`parcel_services` = 1,
	`admin` = 1,
	`emails` = 1,
	`timer` = 1,
	`heidelpaygw` = 1,
	`mailbeez` = 1;
	
INSERT INTO `admin_access` SET
	`customers_id` = 1,
	`configuration` = 1,
	`modules` = 1,
	`countries` = 1,
	`currencies` = 1,
	`zones` = 1,
	`geo_zones` = 1,
	`tax_classes` = 1,
	`tax_rates` = 1,
	`accounting` = 1,
	`backup` = 1,
	`cache` = 1,
	`server_info` = 1,
	`whos_online` = 1,
	`languages` = 1,
	`define_language` = 1,
	`orders_status` = 1,
	`shipping_status` = 1,
	`module_export` = 1,
	`customers` = 1,
	`create_account` = 1,
	`customers_status` = 1,
	`orders` = 1,
	`campaigns` = 1,
	`print_packingslip` = 1,
	`print_order` = 1,
	`popup_memo` = 1,
	`coupon_admin` = 1,
	`listcategories` = 1,
	`gv_queue` = 1,
	`gv_mail` = 1,
	`gv_sent` = 1,
	`validproducts` = 1,
	`validcategories` = 1,
	`mail` = 1,
	`categories` = 1,
	`new_attributes` = 1,
	`products_attributes` = 1,
	`manufacturers` = 1,
	`reviews` = 1,
	`specials` = 1,
	`stats_products_expected` = 1,
	`stats_products_viewed` = 1,
	`stats_products_purchased` = 1,
	`stats_customers` = 1,
	`stats_sales_report` = 1,
	`stats_campaigns` = 1,
	`banner_manager` = 1,
	`banner_statistics` = 1,
	`module_newsletter` = 1,
	`start` = 1,
	`content_manager` = 1,
	`content_preview` = 1,
	`credits` = 1,
	`blacklist` = 1,
	`orders_edit` = 1,
	`popup_image` = 1,
	`csv_backend` = 0,
	`products_vpe` = 1,
	`cross_sell_groups` = 1,
	`listproducts` = 1,
	`gm_scroller` = 1,
	`gm_pdf` = 1,
	`gm_id_starts` = 1,
	`gm_pdf_order` = 1,
	`gm_pdf_action` = 1,
	`gm_emails` = 1,
	`gm_emails_preview` = 1,
	`gm_counter` = 1,
	`gm_counter_action` = 1,
	`gm_meta` = 1,
	`gm_meta_action` = 1,
	`gm_analytics` = 1,
	`gm_bookmarks` = 1,
	`gm_bookmarks_action` = 1,
	`gm_laws` = 1,
	`gm_logo` = 1,
	`gm_security` = 1,
	`gm_style_edit` = 1,
	`gm_send_order` = 1,
	`gm_order_menu` = 1,
	`gm_miscellaneous` = 1,
	`gm_lang_edit` = 1,
	`gm_sitemap` = 1,
	`gm_sitemap_creator` = 1,
	`gm_sql` = 1,
	`gm_offline` = 1,
	`gm_lightbox` = 1,
	`gm_seo_boost` = 1,
	`gm_trusted_shop_id` = 1,
	`gm_opensearch` = 1,
	`gm_opensearch_action` = 1,
	`gm_module_export` = 1,
	`gm_backup_files_zip` = 1,
	`gm_janolaw` = 1,
	`gm_module_part_export` = 1,
	`gm_product_export` = 0,
	`gm_gprint` = 1,
	`gm_gprint_download` = 1,
	`gm_gmotion` = 1,
	`xml_export` = 1,
	`gm_feature_control` = 1,
	`properties` = 1,
	`properties_combis` = 1,
	`request_port` = 1,
	`gm_slider` = 1,
	`template_configuration` = 1,
	`quantity_units` = 1,
	`show_logs` = 1,
	`robots_download` = 1,
	`clear_cache` = 1,
	`directory_scan` = 1,
	`yoochoose` = 1,
	`yatego` = 1,
	`gm_invoicing` = 0,
	`brickfox` = 1,
	`phpminiadmin` = 1,
	`minisql` = 1,
	`ekomi` = 1,
	`magnalister` = 1,
	`mobile` = 1,
	`shopgate` = 1,
	`mediafinanz` = 1,
	`lettr_de` = 1,
	`admin_javascript` = 1,
	`hermes_collection` = 1,
	`hermes_list` = 1,
	`hermes_info` = 1,
	`hermes_order` = 1,
	`hermes_config` = 1,
	`iloxx` = 1,
	`orders_iloxx` = 1,
	`csv` = 1,
	`paypal_config` = 1,
	`paypal_logs` = 1,
	`print_intraship_label` = 1,
	`intraship` = 1,
	`klarna_config` = 1,
	`protectedshops` = 1,
	`itrecht_config` = 1,
	`withdrawals` = 1,
	`findologic_config` = 1,
	`amazonadvpay` = 1,
	`payone_config` = 1,
	`payone_logs` = 1,
	`parcel_services` = 1,
	`admin` = 1,
	`emails` = 1,
	`timer` = 1,
	`heidelpaygw` = 1,
	`mailbeez` = 1;
