DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `categories_id` int(11) NOT NULL AUTO_INCREMENT,
  `categories_image` varchar(64) DEFAULT NULL,
  `parent_id` int(11) NOT NULL DEFAULT '0',
  `categories_status` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `categories_template` varchar(64) DEFAULT NULL,
  `group_permission_0` tinyint(1) NOT NULL DEFAULT '0',
  `group_permission_1` tinyint(1) NOT NULL DEFAULT '0',
  `group_permission_2` tinyint(1) NOT NULL DEFAULT '0',
  `group_permission_3` tinyint(1) NOT NULL DEFAULT '0',
  `listing_template` varchar(64) DEFAULT NULL,
  `sort_order` int(3) NOT NULL DEFAULT '0',
  `products_sorting` varchar(32) DEFAULT NULL,
  `products_sorting2` varchar(32) DEFAULT NULL,
  `date_added` datetime DEFAULT NULL,
  `last_modified` datetime DEFAULT NULL,
  `categories_icon` varchar(255) NOT NULL DEFAULT '',
  `categories_icon_w` int(11) NOT NULL DEFAULT '0',
  `categories_icon_h` int(11) NOT NULL DEFAULT '0',
  `group_ids` varchar(50) NOT NULL DEFAULT '',
  `gm_show_attributes` int(1) unsigned NOT NULL DEFAULT '0',
  `gm_show_graduated_prices` int(1) unsigned NOT NULL DEFAULT '0',
  `gm_show_qty` int(1) unsigned NOT NULL DEFAULT '1',
  `gm_priority` varchar(3) NOT NULL DEFAULT '0.5',
  `gm_changefreq` varchar(255) NOT NULL DEFAULT 'weekly',
  `gm_sitemap_entry` int(1) NOT NULL DEFAULT '1',
  `gm_show_qty_info` int(1) unsigned NOT NULL DEFAULT '0',
  `show_sub_categories` tinyint(1) NOT NULL DEFAULT '1',
  `show_sub_categories_images` tinyint(1) NOT NULL DEFAULT '1',
  `show_sub_categories_names` tinyint(1) NOT NULL DEFAULT '1',
  `show_sub_products` tinyint(1) NOT NULL DEFAULT '0',
  `view_mode_tiled` tinyint(1) NOT NULL DEFAULT '0',
  `feature_mode` int(11) NOT NULL DEFAULT '0',
  `feature_display_mode` int(11) NOT NULL DEFAULT '0',
  `show_category_filter` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`categories_id`),
  KEY `idx_categories_parent_id` (`parent_id`),
  KEY `categories_id` (`categories_id`,`parent_id`,`categories_status`,`sort_order`),
  KEY `parent_id` (`parent_id`,`categories_status`,`sort_order`),
  KEY `categories_status` (`categories_status`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `categories` (`categories_id`, `categories_image`, `parent_id`, `categories_status`, `categories_template`, `group_permission_0`, `group_permission_1`, `group_permission_2`, `group_permission_3`, `listing_template`, `sort_order`, `products_sorting`, `products_sorting2`, `date_added`, `last_modified`, `categories_icon`, `categories_icon_w`, `categories_icon_h`, `group_ids`, `gm_show_attributes`, `gm_show_graduated_prices`, `gm_show_qty`, `gm_priority`, `gm_changefreq`, `gm_sitemap_entry`, `gm_show_qty_info`, `feature_mode`, `feature_display_mode`) VALUES(1, '', 0, 1, 'categorie_listing.html', 0, 0, 0, 0, 'product_listing_v1.html', 0, 'p.products_price', 'ASC', '2008-08-08 17:16:41', '2008-08-25 17:33:52', 'item_ltr.gif', 5, 13, '', 0, 0, 1, '0.5', 'daily', 1, 0, 0, 0);