DROP TABLE IF EXISTS `payone_cr_cache`;
CREATE TABLE `payone_cr_cache` (
  `address_hash` varchar(32) NOT NULL DEFAULT '',
  `address_book_id` int(11) NOT NULL DEFAULT '0',
  `scoretype` varchar(2) NOT NULL DEFAULT '',
  `received` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `secstatus` int(11) NOT NULL DEFAULT '0',
  `status` varchar(7) NOT NULL DEFAULT '',
  `score` varchar(100) NOT NULL DEFAULT '',
  `scorevalue` varchar(100) NOT NULL DEFAULT '',
  `secscore` varchar(100) NOT NULL DEFAULT '',
  `personstatus` varchar(4) NOT NULL DEFAULT '',
  `firstname` varchar(255) NOT NULL DEFAULT '',
  `lastname` varchar(255) NOT NULL DEFAULT '',
  `street` varchar(255) NOT NULL DEFAULT '',
  `streetname` varchar(255) NOT NULL DEFAULT '',
  `streetnumber` varchar(255) NOT NULL DEFAULT '',
  `zip` varchar(255) NOT NULL DEFAULT '',
  `city` varchar(255) NOT NULL DEFAULT '',
  `errorcode` varchar(255) NOT NULL DEFAULT '',
  `errormessage` text NOT NULL,
  `customermessage` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`address_hash`),
  KEY `address_book_id` (`address_book_id`),
  KEY `scoretype` (`scoretype`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;