DROP TABLE IF EXISTS `paypal_ipn`;
CREATE TABLE `paypal_ipn` (
  `paypal_ipn_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `received_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `txn_id` varchar(255) NOT NULL DEFAULT '',
  `address_city` varchar(255) DEFAULT NULL,
  `address_country` varchar(255) DEFAULT NULL,
  `address_country_code` varchar(255) DEFAULT NULL,
  `address_name` varchar(255) DEFAULT NULL,
  `address_state` varchar(255) DEFAULT NULL,
  `address_status` varchar(255) DEFAULT NULL,
  `address_street` varchar(255) DEFAULT NULL,
  `address_zip` varchar(255) DEFAULT NULL,
  `business` varchar(255) DEFAULT NULL,
  `custom` varchar(255) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `invoice` varchar(255) DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `item_number` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `mc_currency` varchar(255) DEFAULT NULL,
  `mc_fee` varchar(255) DEFAULT NULL,
  `mc_gross1` varchar(255) DEFAULT NULL,
  `mc_gross` varchar(255) DEFAULT NULL,
  `mc_handling` varchar(255) DEFAULT NULL,
  `mc_shipping` varchar(255) DEFAULT NULL,
  `notify_version` varchar(255) DEFAULT NULL,
  `parent_txn_id` varchar(255) DEFAULT NULL,
  `payer_email` varchar(255) DEFAULT NULL,
  `payer_id` varchar(255) DEFAULT NULL,
  `payer_status` varchar(255) DEFAULT NULL,
  `payment_date` varchar(255) DEFAULT NULL,
  `payment_status` varchar(255) DEFAULT NULL,
  `payment_type` varchar(255) DEFAULT NULL,
  `pending_reason` varchar(255) NOT NULL DEFAULT '',
  `quantity` varchar(255) DEFAULT NULL,
  `reason_code` varchar(255) DEFAULT NULL,
  `receipt_ID` varchar(255) DEFAULT NULL,
  `receiver_email` varchar(255) DEFAULT NULL,
  `receiver_id` varchar(255) DEFAULT NULL,
  `residence_country` varchar(255) DEFAULT NULL,
  `shipping` varchar(255) DEFAULT NULL,
  `tax` varchar(255) DEFAULT NULL,
  `test_ipn` varchar(255) DEFAULT NULL,
  `txn_type` varchar(255) DEFAULT NULL,
  `verify_sign` varchar(255) DEFAULT NULL,
  `ipn_raw` text,
  `date_test` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`paypal_ipn_id`),
  KEY `txn_id` (`txn_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;