DROP TABLE IF EXISTS `paypal_transactions`;
CREATE TABLE `paypal_transactions` (
  `ecresponse_id` int(11) NOT NULL AUTO_INCREMENT,
  `orders_id` int(11) NOT NULL DEFAULT '0',
  `correlation_id` varchar(255) DEFAULT NULL,
  `ack` varchar(255) DEFAULT NULL,
  `timestamp` datetime DEFAULT NULL,
  `transaction` varchar(255) NOT NULL DEFAULT 'doexpresscheckoutpayment',
  `transaction_id` varchar(255) DEFAULT NULL,
  `parenttransaction_id` varchar(255) DEFAULT NULL,
  `transaction_type` varchar(255) DEFAULT NULL,
  `payment_type` varchar(255) DEFAULT NULL,
  `payment_date` datetime DEFAULT NULL,
  `grossamount` varchar(255) DEFAULT NULL,
  `feeamount` varchar(255) DEFAULT NULL,
  `settleamount` varchar(255) DEFAULT NULL,
  `taxamount` varchar(255) DEFAULT NULL,
  `exchange_rate` varchar(255) DEFAULT NULL,
  `paymentstatus` varchar(255) DEFAULT NULL,
  `payment_error` varchar(255) DEFAULT NULL,
  `expected_echeck_clear_date` varchar(255) DEFAULT NULL,
  `pending_reason` varchar(255) DEFAULT NULL,
  `reason_code` varchar(255) DEFAULT NULL,
  `hold_decision` varchar(255) DEFAULT NULL,
  `protection_eligibility` varchar(255) DEFAULT NULL,
  `protection_eligibility_type` varchar(255) DEFAULT NULL,
  `secure_merchant_account_id` varchar(255) DEFAULT NULL,
  `raw_response` text NOT NULL,
  `success_page_redirect_requested` tinyint(1) DEFAULT NULL,
  `errors` varchar(255) DEFAULT NULL,
  `version_build` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ecresponse_id`),
  KEY `orders_id` (`orders_id`),
  KEY `transaction_id` (`transaction_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;